// NUMBER CONSTANTS
export const WG_COST = 1.75;
export const H_COST = 1.7;
export const HACK_SEC_INCREASE = 0.002;
export const BATCH_BUFFER = 100;
export const SCRIPT_DELAY = 20;
// DEFAULT MONEY % TO HACK
export const HWGW_MONEY_PERCENTAGE = 0.99;
// MIN MONEY % TO HACK, IF NOT POSSIBLE SKIP TARGET\SERVER
export const HWGW_MONEY_MIN_PERCENTAGE = 0.01;
// % TO HACK DIFF TO LOWER
export const HWGW_MONEY_ITERATION_PERCENTAGE = 0.001;
